### ISSUE TITLE
Code not working with basicExamples.tsv

### ISSUE THREAD

**Issue by olivertam** [vishakad/chipulate#1]
Hi,

I cloned chipulate from the git repository today, and tried to run the provided example with the following code:
`python3 chipulate.py -i examples/basicExample.tsv`

I received the following error messages:
```
Traceback (most recent call last):
  File "../software_inst/chipulate/chipulate.py", line 666, in <module>
    main()
  File "../software_inst/chipulate/chipulate.py", line 583, in main
    if terminateFlagInput or terminateFlagBedFasta :
UnboundLocalError: local variable 'terminateFlagBedFasta' referenced before assignment
```
Since I'm not providing an interval file (i.e. no `chr`, `start` and `end` columns), I don't think that it is running the `validateBedFastaAndAutofillInput` subroutine, which assigns the `terminateFlagBedFasta` variable.

I then run into another issue:
```
Traceback (most recent call last):
  File "../software_inst/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../software_inst/chipulate/chipulate.py", line 667, in <module>
    main()
  File "../software_inst/chipulate/chipulate.py", line 616, in main
    pExt=pExt, pcrCycles=pcrCycles, names=inputDf['name'].values,
  File "../software_inst/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "../software_inst/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'
```
At a quick glance, it looks like the `name` column in the input file was not set. Again, I noticed that the code for setting the `name` of the input was found in the `validateBedFastaAndAutofillInput` subroutine (which is skipped).
```python
if 'name' in df.columns:
        df.loc[:,'name'] = df['name'].values
    else:
        df.loc[:,'name'] =  ['region_' + str(idx) for idx in range( 1, df.shape[0]+1 )]
```

I also encountered a third issue:
```
Traceback (most recent call last):
  File "../software_inst/chipulate/chipulate.py", line 673, in <module>
    main()
  File "../software_inst/chipulate/chipulate.py", line 628, in main
    indirectLocations=indirectLocations, generateIntervals=generateIntervals )
UnboundLocalError: local variable 'generateIntervals' referenced before assignment
```
This appears to be also due to the `generateIntervals` variable being initialized only if an interval file is given.

Here are my program versions:

- Python: 3.6.8
- argparse: 1.4.0
- numpy: 1.16.2
- pandas: 0.24.2
- pybedtools: 0.8.0
- scipy: 1.2.1

I am wondering if you had encountered these issues while running `basicExample.tsv`, and if you have any fixes/suggetsions.

Thanks.

**Comment by vishakad** [comment]
I wasn't aware of this issue since the last update of my code. I'll look into this right away. Thanks!

**Comment by vishakad** [comment]
I've fixed the bug now, which was a rather basic one as you pointed out. The issue was, as you said, that terminateFlagBedFasta and generateIntervals were unset when no regions were specified in the input. Similarly, inputDf['name'] was set only when chipulate is run with regions specified in the input. 

Let me know if the examples run fine for you now.

**Comment by olivertam** [comment]
Hi,

Thanks for the quick fix. The code now gets past the setup phase, and appears to go to the computing PCR subroutine. However, it is now throwing a new error:
```
Traceback (most recent call last):
  File "../software_inst/chipulate/chipulate.py", line 674, in <module>
    main()
  File "../software_inst/chipulate/chipulate.py", line 629, in main
    indirectLocations=indirectLocations, generateIntervals=generateIntervals )
  File "../software_inst/chipulate/chipulate.py", line 169, in performChipSeq
    pcrObj = ChipSeq.PCR( pcrCycles, pAmp )
  File "/data/tam/software_inst/chipulate/PCR.py", line 38, in __init__
    self.preComputePCRquantiles( )
  File "/data/tam/software_inst/chipulate/PCR.py", line 73, in preComputePCRquantiles
    self.pcrDistCdf[str(pAmp)] = np.cumsum( self.computePCRdist( pAmp ) )
  File "/data/tam/software_inst/chipulate/PCR.py", line 187, in computePCRdist
    np.save( possFilePath, copyNumberDist )
  File "/data/tam/software_inst/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 517, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'output/pcr-data/15-0.18.npy'
```
This is the code that I ran:
```
$ python3 ../software_inst/chipulate-master/chipulate.py -i ../software_inst/chipulate-master/examples/basicExample.tsv
```

It looks like it is trying to write a file into a subdirectory that does not exist, and might need to be created (e.g. by `mkdir`). I noticed that this folder (`output/pcr-data/`) exists in the source folder (e.g. `chipulate-master`), which suggests that it is assuming the user is running the test within the source folder (i.e. the folder with `chipulate.py`).

Is this feature specific to the test cases (e.g. `basicExample.tsv`)? I also noticed that the output folder is somewhat tracked in the repository (i.e. when I create a file in `output/pcr-data/`, git informs me that it should be added), and thus I was hesitant to run it within the source folder (thus I ran it in a folder elsewhere, as seen in my command line).

Should I run just the test cases in the source folder?
Would it still need the `output/pcr-data/` folders if it is running a non-test case?

Thanks again for all your help.

**Comment by vishakad** [comment]
I have fixed this for now. Thanks for the detailed feedback. It considerably speeds up the time taken for me to fix these issues. I really appreciate the feedback. Let me know if the program runs now.

You should be able to execute the program from anywhere now, not just the source folder. I would urge you to do run the tests from your current folder, and not worry about executing from the source folder.

Regarding your query, the output/pcr-data folder is provided merely to speed up the PCR simulation process for default runs of ChIPulate. It used to take up to an hour to pre-compute PCR distributions when the number of cycles is beyond 12 or 13. You should be able to run chipulate without this directory being in the source folder.

**Comment by olivertam** [comment]
HI,

The program now runs without error using `basicExample.tsv`. 
Thank you again for your quick responses and fixes.

All the best.
