### ISSUE TITLE
Obtaining negative positions in control BED output.

### ISSUE THREAD

**Issue by joshuak94** [vishakad/chipulate#5]
Input file (input.tsv) and control BED file (test100000.control_reads.bed) are attached, after conversion to TXT format for Github's accepted file formats.
[input.txt](https://github.com/vishakad/chipulate/files/3187713/input.txt)
[test100000.control_reads.txt](https://github.com/vishakad/chipulate/files/3187715/test100000.control_reads.txt)

Error message:
```sh
Traceback (most recent call last):
  File "chipulate.py", line 674, in <module>
    main()
  File "chipulate.py", line 638, in main
    makeFastq( bedFileNames, genomeFileName, readLength, libraryType=libraryType )
  File "chipulate.py", line 284, in makeFastq
    regionsFile = pybedtools.BedTool( bedFileName ).getfasta( fi=genomeFileName, bed=bedFileName, s=True, name=True )
  File "/homes/user/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/homes/user/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "/homes/user/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

        bedtools getfasta -s -name -fo /scratch/joshjayk/pybedtools.11hrhckk.tmp -fi examples/yeast-genome.fa -bed test100000/test100000.control_reads.bed

Error message was:
Error: malformed BED entry at line 49076. End Coordinate detected that is < 0. Exiting.
```

The ChIP BED and fastq files were generated fine.

**Comment by vishakad** [comment]
Thanks! I'm looking into this now.

**Comment by vishakad** [comment]
Can you check with the latest commit if this issue is fixed for you? Also, this should remove the need for a sorted BED file that you had pointed out on a different thread.
